### ISSUE TITLE
Why group channels, or how to disable it?

### ISSUE THREAD

**Issue by jezokshe** [efoxbr/megacubo#19]
I wish it were easier

**Comment by efoxbr** [comment]
@bamper45 I don't know if I understood your point, but if you want to use the organization of your IPTV list instead of the channel list in the "Live" section, just go to IPTV Lists > My Lists > List name.

If so, let me know, we can rethink this part.

**Comment by bamper45** [comment]
This is how they are grouped. Although there are no groups at all in the sheet
![изображение](https://user-images.githubusercontent.com/77186394/202232227-0ce88344-4996-4d91-9e5d-334c2014eb2f.png)

**Comment by efoxbr** [comment]
@bamper45 I did it this way to prevent very large listings. Because I saw poorly organized lists that caused folders with more than a thousand files, causing slowness in the interface. But I understand that this can be unwanted and confusing.

In the next version I will include an option to define how many items the folder must have so that there is pagination, so the user just needs to set it to a high amount.

**Comment by bamper45** [comment]
@efoxbr It is clear, but I think one more parameter, without grouping, will not interfere. I think most people don't have such big lists. I've tried smartphones and Windows, both of which lead to extra clicks. You have to constantly switch back and forth.
