### ISSUE TITLE
Error iptv list

### ISSUE THREAD

**Issue by erickants** [efoxbr/megacubo#2]
My iptv list get this error: 

> Player error: mediaError - fragParsingError

**Comment by efoxbr** [comment]
That's a hls.js error. https://github.com/video-dev/hls.js/issues/135

It may be related to the codec used in the IPTV list. For streams ending in .ts instead of .m3u8, the program uses FFmpeg to transform it in a M3U8 compatible with the HTML5 video player + hls.js. But as transcoding the video would be too resource intensive, it uses "copy" instead of "libx264" as the output video codec parameter on FFmpeg.

If the codec used by the .ts stream isn't compatible with HTML5 video, then is explains this error.

**Comment by efoxbr** [comment]
I can implement a transcoding option unchecked by default, just for completeness, but personally I think it will not mush usable, my CPU gets crazy transcoding even SD streams.

Other possibility would be something like WebChimera, but that seemed too complex at a first look.
