### ISSUE TITLE
v16.8.1 broadcast server overloaded.

### ISSUE THREAD

**Issue by musawershah1598** [efoxbr/megacubo#26]
Hi whenever i try to run a file in my playlist it always show the `The broadcast server seems overloaded` Can you help me with that. What is the issue. I had used the same iptv playlist on my mobile on other app over there it works fine. But when i try to run it on laptop on megacubo it shows this error. My OS is ubuntu 22.04. Thanks

**Comment by andekande** [comment]
I occasionally get these messages as well, but they disappear also. Seems to be related to the buffering of the stream.
This was recently changed with version [16.8.3](https://github.com/efoxbr/megacubo/releases/tag/v16.8.3) which should have less of these messages.

**Comment by efoxbr** [comment]
Hi @musawershah1598, there are two possible scenarios:

- If you are using public lists (Community Lists)

When watching a channel, if the live transmission is slow or you have any other problem, follow the step-by-step link below so that Megacubo opens another transmission of the same channel automatically.

https://megacubo.tv/en/broadcast-problem/

- If you are using your own playlist or watching VOD

In this case, the slowdown is caused by your own connection or the origin server, not the application itself. **Especially if the app is up to date**, as the latest versions have received several performance improvements.
