### ISSUE TITLE
Where is MacOS .dmg file??

### ISSUE THREAD

**Issue by basha318i** [efoxbr/megacubo#29]
There's no MacOS .dmg file!

**Comment by efoxbr** [comment]
@basha318i I'm a PC user and I generated the Mac versions through VMWare, but due to a problem I had on my computer I ended up losing the HDD where this VM was.

As soon as I have time I will redo it, until then, the [last version that is available for macOS is 16.7.4](https://github.com/efoxbr/megacubo/releases/tag/v16.7.4).

**Comment by efoxbr** [comment]
I'm closing this issue in favor of issue #28.

**Comment by efoxbr** [comment]
Hello @basha318i, I have now added the DMG file in the [version 17.2.6 release](https://github.com/efoxbr/megacubo/releases/tag/v17.2.6).

**Comment by basha318i** [comment]
Thanks a lot!
