### ISSUE TITLE
 Slow streaming

### ISSUE THREAD

**Issue by tecbeto** [efoxbr/megacubo#3]
Hello, I installed Megacubo on Linux Ubuntu 19.10. I have 35mb of internet and the HD is SSD, but the transmission is pausing on all channels. What can I do to optimize the connection? Some channels do not display video, only audio. I ask for help on this problem as well. Thanks.

**Comment by efoxbr** [comment]
Hi @tecbeto , this problem is related to the source server of the transmission.

Unless you add a paid or quality guaranteed IPTV list, the program will use free lists added by other users.

Many transmissions from these lists point to overloaded, remote or low quality servers for the transmission.

Possible solutions:

1. Choose "exclusive mode" when installing the program and add a quality IPTV list.

2. Or, using free lists, when a transmission has any problems, press Ctrl + Tab (change transmission) to open another transmission of the same channel until you find a suitable one.

The screen goes black when the codec used in the transmission is incompatible with HTML5, in which case the above procedure is also recommended.
