### ISSUE TITLE
Add to Play Store

### ISSUE THREAD

**Issue by Penknife0915** [efoxbr/megacubo#30]
Adding it to the Play Store would offer users a convenient and secure way to access the app.

You may also want to take a look at Accrescent:
https://accrescent.app/
https://accrescent.app/docs/index.html

**Comment by efoxbr** [comment]
Hi @Penknife0915, Megacubo was on the Play Store but was removed by Google, due to the community lists feature I believe.

Thanks for the suggestion, but when registering in Accrescent's Developer Console I got the message below:

"Registration not permitted
Accrescent developer registration is currently invite-only. Please come back when registration opens for everyone."
