### ISSUE TITLE
Wordpress/Blogger embed. m3u vs m3u8. Youtube support.

### ISSUE THREAD

**Issue by siliconhippy** [efoxbr/megacubo#9]
Hi efoxbr !

Looks like great work.

1. Can this be embedded in a wordpress.org or blogger.com page ?

Noob here, but it is frustrating to see that big names like JWP (expensive + BW charges + no Youtube support) don't seem to play my m3u/8 playlist URL, or this kind of public IPTV one (both play fine in VLC or smartIPTV chrome extension):

https://iptv-org.github.io/iptv/countries/ca.m3u

(doesn't play in https://hls-js.netlify.app/demo/ or https://developer-tools.jwplayer.com/stream-tester/ )

2. Is this an m3u to m3u8 conversion issue you might support ? (Should be simple.)

3. Does your player support youtube https URLs, or some m3u/8 conversion (e.g., streamlink/liveproxy or VLC conversion of youtube http URL Network Stream  input to Codec Info link (bottom box) saved to a m3u playlist ?)

Cheers,
Shippy.

**Comment by efoxbr** [comment]
Hi @siliconhippy, thanks!

1. No. Megacubo is not embeddable on web pages, it is a desktop/mobile app. It would be quite problematic to reproduce streams from different sources, as Megacubo does, on a webpage due to CORS-related issues.

2. When talking about IPTV, the M3U file is a playlist that contains several M3U8 links in it, so it doesn't make much sense to convert M3U to M3U8.

M3U = Playlist with many live (or VOD) streams
M3U8 = Stream URL

Players like JWPlayer and HLS.js play M3U8 links unless there are CORS-related issues between the streaming origin server and the server hosting the player.

3. Megacubo doesn't support Youtube links directly yet. The focus is on direct links from videos and streams to be compatible with IPTV M3U playlists.
